galera-node1:
    build: galera/
    privileged: true
    command: mysqld_safe
    volumes:
        - /etc/mysql:/opt/etc/galera
        - /var:/opt/galera1

galera-node2:
    build: galera/
    privileged: true
    command: mysqld_safe
    volumes:
        - /etc/mysql:/opt/etc/galera
        - /var:/opt/galera2
    links:
        - galera-node1

galera-node3:
    build: galera/
    privileged: true
    command: mysqld_safe
    volumes:
        - /etc/mysql:/opt/etc/galera
        - /var:/opt/galera3
    links:
        - galera-node1

