galera-node1:
    build: .
    privileged: true
    command: bash -c "mysql_install_db && mysqld --wsrep-new-cluster"
    volumes:
        - /opt/etc/mysql.conf.d:/etc/mysql/conf.d
        - /opt/galera1:/var/lib/mysql

galera-node2:
    build: .
    privileged: true
    command: bash -c "mysql_install_db && mysqld_safe"
    volumes:
        - /opt/etc/mysql.conf.d:/etc/mysql/conf.d
        - /opt/galera2:/var/lib/mysql
    links:
        - galera-node1

galera-node3:
    build: .
    privileged: true
    command: bash -c "mysql_install_db && mysqld_safe"
    volumes:
        - /opt/etc/mysql.conf.d:/etc/mysql/conf.d
        - /opt/galera3:/var/lib/mysql
    links:
        - galera-node1

