version: '2'
node1:
    build: .
    privileged: true
    command: bash -c "mysqld_safe"
    volumes:
        - /opt/etc/mysql:/etc/mysql/
        - /opt/galera1:/var/lib/mysql

node2:
    build: .
    privileged: true
    command: bash -c "mysqld_safe"
    volumes:
        - /opt/etc/mysql.conf.d:/etc/mysql/conf.d
        - /opt/galera2:/var/lib/mysql
    links:
        - node1

node3:
    build: .
    privileged: true
    command: bash -c "mysqld_safe"
    volumes:
        - /opt/etc/mysql.conf.d:/etc/mysql/conf.d
        - /opt/galera3:/var/lib/mysql
    links:
        - node1
