version: '2'

services:
    ubuntu-setup:
        build: ./ubuntu
        image: openstack:ubuntu
        container_name: base_image
    galera-master:
        build: ./galera
        image: openstack:galera
        container_name: galera_master
    galera-node2:
        image: openstack:galera
        container_name: galera-node2
    galera-node3:
        image: openstack:galera
        container_name: galera-node3
    puppet-master:
        build: ./puppet-master
        image: openstack:puppet-master
        container_name: puppet-master
        command: service apache2 restart
        ports:
            - 3140:3140
    puppet-agent:
        build: ./puppet-agent
        image: openstack:puppet-agent
        container_name: puppet-agent
    barbican:
        build: ./barbican
        image: openstack:barbican
        container_name: os-barbican
    cinder:
        build: ./cinder
        image: openstack:cinder
        container_name: os-cinder
    designate:
        build: ./designate
        image: openstack:designate
        container_name: os-designate
    glance:
        build: ./glance
        image: openstack:glance
        container_name: os-glance
    heat:
        build: ./heat
        image: openstack:heat
        container_name: os-heat
    horizon:
        build: ./horizon
        image: openstack:horizon
        container_name: os-horizon
    ironic:
        build: ./ironic
        image: openstack:ironic
        container_name: os-ironic
    keystone:
        build: ./keystone
        image: openstack:keystone
        container_name: os-keystone
    magnum:
        build: ./magnum
        image: openstack:magnum
        container_name: os-magnum
    neutron:
        build: ./neutron
        image: openstack:neutron
        container_name: os-neutron
    nova:
        build: ./nova
        image: openstack:nova
        container_name: os-nova
